### ISSUE TITLE
dissect is required for installation

### ISSUE THREAD

**Issue by t-cool** [fukamachi/utopian#2]
I was faced with the following issue when I tried installing utopian.
After installing Shinmera's dissect, I made it.

```
$ ros install fukamachi/utipian
…
…
…
[package dissect]
[91m[1/3] System 'utopian' found. Loading the system..
[91m; caught ERROR:
[91m;   READ error during COMPILE-FILE:
[91m;     Symbol "DEBUG-SOURCE-FORM" not found in the SB-DI package.
[91m;       Line: 18, Column: 43, File-Position: 562
[91m;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /root/.roswell/lisp/quicklisp/dists/quicklisp/software/dissect-20180131-git/backend/sbcl.lisp" 
```

https://hub.docker.com/r/tcool/cl-ubuntu/builds/

https://hub.docker.com/r/tcool/cl-alpine/builds/

**Comment by fukamachi** [comment]
Internal API changes of SBCL 1.4.10 broke dissect.
It's already fixed in the latest dissect, which you can get it from GitHub.

I guess that you could resolve the error because you installed the latest version by `ros install Shinmera/dissect`.

**Comment by t-cool** [comment]
I see... Now maybe I understand the reason.  When I tried installing utopian, I imported the old version of dissect, which was not fixed for sbcl 1.4.10.  I looked up its version on quicklisp, and the version was dissect-20180131.git.

By the time the dissect is updated on quicklisp, do we need to install dissect manually?

**Comment by fukamachi** [comment]
Not necessary.
